/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crisimimis;


import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author caibugatti.ruben
 */
public class PannelloDiControlloFabbrica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PannelloDiControlloFabbrica.class.getName());

    /**
     * Creates new form pannelloDiControlloFabbrica
     */
    CatenaDiMontaggio catena=new CatenaDiMontaggio();
    Timer t;
    String pacco;
    public int r=0;
    Giocattolo g;
    int[] pos={80,195,330,450};
    int[] fermarsi;
    
    public PannelloDiControlloFabbrica() {
      
        initComponents();

        jTextArea1.setEditable(false);
        JLabel[] regali={jLabel24,jLabel2,jLabel29};
        jTextField1.setPreferredSize(new Dimension(64, 22));
        jLabel22.setBounds(870, 20, 100, 30);
        JLabel[] label={jLabel12,jLabel13,jLabel14,jLabel15};
        JLabel[] label1={jLabel25,jLabel26,jLabel27,jLabel28};
        
        
        int[] x = {0}; 
        
        t = new Timer(10, e -> {

            if(jLabel22.getY()==670){
                jLabel22.setIcon(null);
                jLabel22.setLocation(870, 20);
                regali[r].setIcon(new ImageIcon((URL)getClass().getResource(pacco)));
                x[0]=20;
                t.stop();
                r++;
                jTextArea1.append(g.toString()+"\n");
                
                jButton1.setEnabled(true);
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
                catena.pulisciElfi();
                catena.pulisciMacchinari();
                for(JLabel j:label){
                    j.setIcon(null);
                }
                for(JLabel j:label1){
                    j.setIcon(null);
                }
                i=0;
                p=0;
                jLabel10.setText("");
                jTextField1.setText("");
            }
            else{
                for(int i=0;i<fermarsi.length;i++){
                    if(jLabel22.getY()==fermarsi[i]){
                        t.stop();
                        
                        Timer pausa = new Timer(1000, a -> {t.start();});
                        pausa.setRepeats(false);
                        pausa.start();

                    }
                }
                
                x[0] += 1;
                jLabel22.setLocation(870, x[0]);
            }
            
            
        });
        
        
    }

    public int i=0;
    public int p=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        jLabel23.setText("jLabel23");

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crisimimis/Immagini/Immagine 2025-12-02 130217.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 310, 0, 296));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 305, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLASTICA", "LEGNO", "FERRO", "CRISTALLODINEVE", "FRAMMENTOMAGICO" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel4.setText("SCEGLI IL MATERIALE DEL TUO GIOCATTOLO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 62, -1, -1));

        jButton1.setText("SCEGLI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel5.setText("SCEGLI IL TIPO DI MATERIALE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel6.setText("MATERIALE SCELTO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel7.setText("SCEGLI GLI ELFI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 91, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELFO PROGETTATORE", "ELFO ASSEMBLATORE", "ELFO NEVICATORE", "ELFO MAGICO", "ELFO CONTROLLORE" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 204, -1));

        jButton2.setText("SCEGLI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel8.setText("SCEGLI I MACCHINARI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 120, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MACCHINARIO PROGETTATORE", "MACCHINARIO ASSEMBLATORE", "MACCHINARIO NEVICATORE", "MACCHINARIO MAGICO", "MACCHINARIO CONTROLLORE" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jButton3.setText("SCEGLI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1461, 49, -1, -1));

        jButton4.setText("MONTA IL GIOCO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 60, 20));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 80, 90));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 60, 90));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 70, 110));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, 60, 110));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crisimimis/Immagini/Immagine_2025-12-02_131258-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 610, 320, -1));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 70, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crisimimis/Immagini/rulli.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, -90, 100, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crisimimis/Immagini/rulli.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 100, -1));

        jLabel19.setText("QUESTA E' LA QUALITA' DEL GIOCO");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel11.setText("SCEGLI I MACCHINARI");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 120, -1, -1));

        jLabel20.setText("SCEGLI I MACCHINARI");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 120, -1, -1));

        jLabel21.setText("NOME DEL GIOCATTOLO:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 70, 60));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 70, 90));
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 70, 90));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 70, 110));
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 70, 110));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 70, 60));
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 80, 80));

        jLabel30.setText("GIOCATTOLI GIA FATTI");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 410, 240));

        jButton5.setText("ISTRUZIONI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        catena.mat((String)jComboBox1.getSelectedItem());
        jLabel5.setText(catena.getNomeMat());
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JLabel[] label={jLabel12,jLabel13,jLabel14,jLabel15};
        String cod=catena.creoElfo((String) jComboBox2.getSelectedItem());
        if(cod!=""){
           if(i<4){
                label[i].setIcon(new ImageIcon((URL)getClass().getResource(cod)));
                i++;
            }    
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        fermarsi=new int[catena.elfi.size()];
        for(int i=0; i<catena.elfi.size();i++){
            fermarsi[i]=pos[i];
        }
        int ris=0; 
        boolean ok=false;
        for (Elfo elfo : catena.elfi) {
            if (elfo instanceof ElfoProgettatore) {
                if(catena.macchinari.get(catena.elfi.indexOf(elfo)) instanceof MacchinarioProgettatore){
                    ok =true;
                }
                ris+=((ElfoProgettatore) elfo).Progetta(catena.materiale,ok);
            } 
            else if (elfo instanceof ElfoAssemblatore) {
                if(catena.macchinari.get(catena.elfi.indexOf(elfo)) instanceof MacchinarioAssemblatore){
                    ok =true;
                }
                ris+=((ElfoAssemblatore) elfo).Assembla(catena.materiale,ok);
            } 
            else if (elfo instanceof ElfoNevicatore) {
                if(catena.macchinari.get(catena.elfi.indexOf(elfo)) instanceof MacchinarioNevicatore){
                    ok =true;
                }
                ris+=((ElfoNevicatore) elfo).Nevica(catena.materiale,ok);
            } 
            else if (elfo instanceof ElfoMagico) {
                if(catena.macchinari.get(catena.elfi.indexOf(elfo)) instanceof MacchinarioMagico){
                    ok =true;
                }
                ris+=((ElfoMagico) elfo).Magia(catena.materiale,ok);
            } 
            else if (elfo instanceof ElfoControllore) {
                if(catena.macchinari.get(catena.elfi.indexOf(elfo)) instanceof MacchinarioControllore){
                    ok =true;
                }
                ris+=((ElfoControllore) elfo).Controlla(catena.elfi.size(),ok);
            }
        }
        for (Macchinario mac : catena.macchinari) {
            if (mac instanceof MacchinarioProgettatore) {
                ris+=((MacchinarioProgettatore) mac).progetto(catena.macchinari.indexOf(mac));
            } 
            else if (mac instanceof MacchinarioAssemblatore) {
                ris+=((MacchinarioAssemblatore) mac).assembla(catena.macchinari.indexOf(mac));
            } 
            else if (mac instanceof MacchinarioNevicatore) {
                ris+=((MacchinarioNevicatore) mac).neve(catena.macchinari.indexOf(mac));
            } 
            else if (mac instanceof MacchinarioMagico) {
                ris+=((MacchinarioMagico) mac).magia(catena.macchinari.indexOf(mac));
            } 
            else if (mac instanceof MacchinarioControllore) {
                ris+=((MacchinarioControllore) mac).controllo(catena.macchinari.indexOf(mac));
            }
        }
        
        g=catena.creoGioco(ris,jTextField1.getText());
        this.pacco=catena.sceltaPacco();
        jLabel22.setIcon(new ImageIcon((URL)getClass().getResource(pacco)));
        t.start();
        
        
        jLabel10.setText(String.valueOf(ris));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JLabel[] label={jLabel25,jLabel26,jLabel27,jLabel28};
        String cod=catena.creoMacchinario((String) jComboBox3.getSelectedItem());
        if(cod!=""){
           if(p<4){
                label[p].setIcon(new ImageIcon((URL)getClass().getResource(cod)));
                p++;
            } 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(
            null,
            "La fabbrica di Babbo Natale è composta da quattro postazioni di lavoro,\n" +
            "ognuna pronta ad accogliere un solo elfo alla volta.\n" +
            "Ogni elfo ha un nome tutto suo, lavora con un materiale specifico\n" +
            "e può utilizzare un macchinario per creare i giocattoli.\n" +
            "Tuttavia, ogni elfo ha anche un macchinario preferito:\n" +
            "quando lavora con quello giusto, diventa più veloce, preciso\n" +
            "e la magia del Natale si sente di più!\n" +
            "Combinando nel modo migliore elfi, materiali e macchinari,\n" +
            "la fabbrica riesce a produrre splendidi giochi\n" +
            "da consegnare a Babbo Natale per rendere felici tutti i bambini 🎁✨",
            "FABBRICA DI BABBO NATALE",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PannelloDiControlloFabbrica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
